---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: dev
  labels:
    appname: mongo
    appcomp: backend
    appenv: dev
spec:
  selector:
    matchLabels:
        appname: mongo
        appcomp: backend
        appenv: dev
  replicas: 1
  template:
    metadata:
      labels:
        appname: mongo
        appcomp: backend
        appenv: dev
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dev
  labels:
    appname: mongo
    appcomp: backend
    appenv: dev
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    appname: mongo
    appcomp: backend
    appenv: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    appname: guestbook
    appcomp: frontend
    appenv: dev
spec:
  selector:
    matchLabels:
      appname: guestbook
      appcomp: frontend
      appenv: dev
  replicas: 3
  template:
    metadata:
      labels:
        appname: guestbook
        appcomp: frontend
        appenv: dev
    spec:
      containers:
      - name: guestbook
        image: paulczar/gb-frontend:v5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dev-front
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30080
  selector:
    appname: guestbook
    appcomp: frontend
    appenv: dev
